# python train.py 0 0 xception
# python train.py 0 0 meso
# python train.py 0 0 mesoinception
# python train.py 0 0 fwa
# python train.py 0 0 dsp-fwa
# python train.py 0 0 capsule
# python train.py 1 0 xception
# python train.py 1 0 meso
# python train.py 1 0 mesoinception
# python train.py 1 0 fwa
# python train.py 1 0 dsp-fwa
# python train.py 1 0 capsule
# python train.py 2 0 xception
# python train.py 2 0 meso
# python train.py 2 0 mesoinception
# python train.py 2 0 fwa
# python train.py 2 0 dsp-fwa
# python train.py 2 0 capsule
# python train.py 0 1 xception
# python train.py 0 1 meso
# python train.py 0 1 mesoinception
# python train.py 0 1 fwa
# python train.py 0 1 dsp-fwa
# python train.py 0 1 capsule
# python train.py 1 1 xception
# python train.py 1 1 meso
# python train.py 1 1 mesoinception
# python train.py 1 1 fwa
# python train.py 1 1 dsp-fwa
# python train.py 1 1 capsule
# python train.py 2 1 xception
# python train.py 2 1 meso
# python train.py 2 1 mesoinception
# python train.py 2 1 fwa
# python train.py 2 1 dsp-fwa
# python train.py 2 1 capsule